import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import OrderForm from "@/components/OrderForm";
const savedOrder={orderId:"MC-1234",customerName:"Test Customer",mobile:"9876543210",address:"Flat 1204, Tower A",items:[{cupSize:"500 ML",flavour:"Blueberry",quantity:2,unitPrice:159,lineTotal:318}],totalPrice:318,preferredDateTime:"2026-09-03T06:00:00.000Z"};
beforeEach(()=>{vi.useFakeTimers({shouldAdvanceTime:true});vi.setSystemTime(new Date("2026-09-03T10:00:00+05:30"));vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,json:async()=>({order:savedOrder,whatsappNumber:"919876543210"})}));});
afterEach(()=>{cleanup();vi.useRealTimers();vi.unstubAllGlobals();});
async function placeOrder(){render(<OrderForm/>);fireEvent.change(screen.getByLabelText("Name"),{target:{value:savedOrder.customerName}});fireEvent.change(screen.getByLabelText("WhatsApp number"),{target:{value:savedOrder.mobile}});fireEvent.change(screen.getByLabelText("Tower (required)"),{target:{value:"A"}});fireEvent.change(screen.getByLabelText("Enter floor and flat no. (required)"),{target:{value:"1204"}});fireEvent.click(screen.getByRole("button",{name:"Add one Blueberry 500 ML"}));fireEvent.click(screen.getByRole("button",{name:"Add one Blueberry 500 ML"}));fireEvent.click(screen.getAllByRole("button",{name:/10:30/i})[0]);fireEvent.click(screen.getByRole("button",{name:/Place Order/}));return await screen.findByRole("dialog");}
describe("order confirmation flow",()=>{
 it("shows multi-item summary and keeps modal open after WhatsApp",async()=>{const dialog=await placeOrder();expect(within(dialog).getByText(/2 × Blueberry/)).toBeInTheDocument();const link=within(dialog).getByRole("link",{name:"Send Order on WhatsApp"});link.addEventListener("click",e=>e.preventDefault(),{once:true});fireEvent.click(link);expect(within(dialog).getByRole("heading",{name:"Thank you for your order!"})).toBeInTheDocument();expect(within(dialog).getByRole("button",{name:"Close"})).toBeInTheDocument();});
 it("resets products after closing",async()=>{const dialog=await placeOrder();fireEvent.click(within(dialog).getByRole("button",{name:"Close order details"}));expect(screen.getByText("Choose your Matcha to start your order 🍵")).toBeInTheDocument();expect(screen.getByRole("button",{name:/Place Order/})).toBeDisabled();});
});
